# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Notebook for Things I've Learned and Done"
tagline:          
description:      "Passion, purpose, and mastery comes from consistent effort."
url:              
baseurl:          /
caturl:           /categories/

author:
  name:           'Rushan Chen'
  url:            

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
